- name: Install  mongodb
  apt:
    name: mongodb
    state: present
  become: yes

- name: Start mongodb
  service:
    name: mongodb
    state: started
  become: yes
  
- name: Check MongoDB Status
  service:
    name: mongodb
    state: started
  register: mongodb_status

- name: print mongodb status
  debug:
    var: mongodb_status.state