- name: install free5gc
  hosts: all
  vars_files:
    - "./vars.yaml"
  tasks:
    - name: Set ansible environment variables
      set_fact:
        ansible_env:
          PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
          GOPATH: "{{ ansible_env.HOME }}/go"
          GOROOT: "/usr/local/go"
          GO111MODULE: "auto"
          HOME: "{{ ansible_env.HOME }}"
        
    - name: Include roles
      include_role:
        name: "{{ item }}"
      with_items:
        - kernel_version
        - tools
        - mongodb
        - Golang
        - free5gc
        - gtp5g
        - webConsole
