---
- name: Build and Install free5GC
  hosts: all
  vars:
    home_path: "/home/miski"

  tasks:
# --------------------- Install Prerequisites -------------------------------------
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Prerequisites
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - gcc
        - g++
        - cmake
        - autoconf
        - libtool
        - pkg-config
        - libmnl-dev
        - libyaml-dev
      become: yes

    - name: Install  mongodb
      apt:
        name: mongodb
        state: present
      become: yes

    - name: Start mongodb
      service:
        name: mongodb
        state: started
      become: yes

    - name: Download Go binary
      get_url:
        url: "https://dl.google.com/go/go1.18.10.linux-amd64.tar.gz"
        dest: "{{ home_path }}/go1.18.10.linux-amd64.tar.gz"
   
    - name: Extract Go binary
      unarchive:
        src: "{{ home_path }}/go1.18.10.linux-amd64.tar.gz"
        dest: "/usr/local/"
        remote_src: yes
        mode: '0755'

      become: true
    
    - name: Create Go directories
      file:
        path: "{{ home_path }}/go/{{ item }}"
        state: directory
      loop:
        - "bin"
        - "pkg"
        - "src"
      
    - name: Add environment variables to .bashrc
      lineinfile:
        path: "{{ home_path }}/.bashrc"
        line: "{{ item }}"
        create: yes
      loop:
          - "export GOPATH={{ home_path }}/go"
          - "export GOROOT=/usr/local/go"
          - "export PATH=$PATH:$GOPATH/bin:$GOROOT/bin"
          - "export GO111MODULE=auto"
    - name: Get Go version
      command: /usr/local/go/bin/go version
      register: go_version_output
    - name: Print Go version
      debug:
        msg: "{{ go_version_output.stdout }}"

# --------------------- Install Control Plane Elements -------------------------------------

    - name: Clone Free5GC repository
      git:
        repo: "https://github.com/free5gc/free5gc.git"
        dest: "{{ home_path }}/free5gc"
        version: "v3.3.0"
        recursive: yes
        accept_hostkey: yes  # To avoid SSH key checking if using SSH
        clone: yes

    - name: build all network functions
      command: /usr/bin/make
      args:
        chdir: "{{ home_path }}/free5gc"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ home_path }}/go/bin:/usr/local/go/bin"

# --------------------- Install User Plane Function (UPF) -------------------------------------

    - name: clone User Plane Function (UPF)
      git: 
        repo:  "https://github.com/free5gc/gtp5g.git"
        dest:  "{{ home_path }}/gtp5g"
        version: "v0.8.5"
        recursive: yes
        accept_hostkey: yes
        clone: yes

    - name: build User Plane Function (UPF) STEP1
      make:
        chdir: "{{ home_path }}/gtp5g"
  
    - name: build User Plane Function (UPF) STEP2
      become: true
      make:
        chdir: "{{ home_path }}/gtp5g"
        target: install

# ---------------------  Install WebConsole  -------------------------------------
    - name: Installing Nodejs
      get_url:
        url: "https://deb.nodesource.com/setup_20.x"
        dest: ~/nodejs
        mode: 0755
      become: true

    - name: Nodejs Package
      command: ~/nodejs
      args:
        creates: /etc/apt/sources.list.d/nodesource.list
      become: true
    - name: Yarn GPG
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present
      become: true

    - name: Importing Yarn Package
      copy:
        content: "deb https://dl.yarnpkg.com/debian/ stable main"
        dest: /etc/apt/sources.list.d/yarn.list
      become: true

    - name: Installing Nodejs + Yarn
      apt:
        name:
          - nodejs
          - yarn
        update_cache: true
      become: true

    - name: Make webconsole
      command:  "/usr/bin/make  webconsole"
      args:
        chdir: "{{ home_path }}/free5gc"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ home_path }}/go/bin:/usr/local/go/bin"
      register: make_result
  
    - name: Debug make_result
      debug:
        var: make_result

    - name: Proceed if webconsole is successfully built
      debug:
        msg: "Webconsole was successfully built"
      when: not make_result.failed
