---
- name: Install Prerequisites for Free5GC
  hosts: all
  become: yes
# bug :  ansible_env.HOME 
  tasks:
    # - name: Update apt cache
    #   apt:
    #     update_cache: yes
    #   become: yes

    # - name: Install Prerequisites
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #   with_items:
    #     - git
    #     - gcc
    #     - g++
    #     - cmake
    #     - autoconf
    #     - libtool
    #     - pkg-config
    #     - libmnl-dev
    #     - libyaml-dev
    #   become: yes

    # - name: Install  mongodb
    #   apt:
    #     name: mongodb
    #     state: present
    #   become: yes

    # - name: Start mongodb
    #   service:
    #     name: mongodb
    #     state: started
    #   become: yes

    - name: Download Go binary
      get_url:
        url: "https://dl.google.com/go/go1.18.10.linux-amd64.tar.gz"
        dest: "{{  ansible_env.HOME  }}/go1.18.10.linux-amd64.tar.gz"
        mode: '0644'
   
    - name: Extract Go binary
      unarchive:
        src: "{{ ansible_env.HOME }}/go1.18.10.linux-amd64.tar.gz"
        dest: "/usr/local/"
        remote_src: yes
    
    - name: Create Go directories
      file:
        path: "{{ ansible_env.HOME }}/go/{{ item }}"
        state: directory
      loop:
        - "bin"
        - "pkg"
        - "src"

    - name: Add environment variables to .bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ item }}"
        create: yes
      loop:
        - "export GOPATH={{ ansible_env.HOME }}/go"
        - "export GOROOT=/usr/local/go"
        - "export PATH=$PATH:{{ ansible_env.HOME }}/go/bin:/usr/local/go/bin"
        - "export GO111MODULE=auto"
   
