- name: Install dependencies for Docker
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: Add Docker GPG apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  become: true
  package:
    name: docker-ce
    state: present

- name: Start Docker service
  become: true
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to the Docker group
  become: true
  shell: "usermod -aG docker {{ ansible_ssh_user }}"
  args:
    executable: /bin/bash