- name: Installing Nodejs
  get_url:
    url: "https://deb.nodesource.com/setup_20.x"
    dest: ~/nodejs
    mode: 0755
  become: true

- name: Nodejs Package
  command: ~/nodejs
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
  become: true
- name: Yarn GPG
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  become: true

- name: Importing Yarn Package
  copy:
    content: "deb https://dl.yarnpkg.com/debian/ stable main"
    dest: /etc/apt/sources.list.d/yarn.list
  become: true

- name: Installing Nodejs + Yarn
  apt:
    name:
      - nodejs
      - yarn
    update_cache: true
  become: true

- name: Make webconsole
  command:  "/usr/bin/make  webconsole"
  args:
    chdir: "~/free5gc"
  environment: "{{ ansible_env }}"
  register: make_result

- name: Debug make_result
  debug:
    var: make_result
  no_log: true


- name: Proceed if webconsole is successfully built
  debug:
    msg: "Webconsole was successfully built"
  when: not make_result.failed