- name: Create bin directory
  become: true
  file:
    path: /home/bin
    state: directory
    mode: "0755"

- name: Copy script files to the remote server
  become: true
  copy:
    src: "{{ item }}"
    dest: "/home/bin/{{ item | basename }}"
    mode: "0755"
  with_fileglob:
    - "{{ role_path }}/files/*"

- name: Append export statement to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:/home/bin'
    insertafter: EOF

- name: Source .bashrc
  shell: "source ~/.bashrc"
  args:
    executable: /bin/bash