- name: Download Go binary
  get_url:
    url: "https://dl.google.com/go/go{{golang.version}}.linux-amd64.tar.gz"
    dest: "/tmp/go{{golang.version}}.linux-amd64.tar.gz"

- name: Extract Go binary
  unarchive:
    src: "/tmp/go{{golang.version}}.linux-amd64.tar.gz"
    dest: "/usr/local/"
    remote_src: yes
    mode: '0755'

  become: true

- name: Create Go directories
  file:
    path: "~/go/{{ item }}"
    state: directory
  loop:
    - "bin"
    - "pkg"
    - "src"

- name: Update .bashrc with Go environment variables
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
    create: yes
  loop:
    - "export PATH=$PATH:/usr/local/go/bin"
    - "export GOPATH={{ ansible_env.HOME }}/go"
    - "export GOROOT=/usr/local/go"
    - "export GO111MODULE=auto"

- name: Source .bashrc to apply changes
  shell: "source ~/.bashrc"
  args:
    executable: /bin/bash

- name: Get Go version
  command: go version
  environment: "{{ ansible_env }}"
  register: go_version_output

- name: print Go Version
  debug:
    var: go_version_output.stdout