#!/bin/bash
sudo sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1 & 
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo systemctl stop ufw
sudo iptables -I FORWARD 1 -j ACCEPT
docker exec -it ue_test bash -c "ping -I uesimtun0 google.com"